name: smart_actions
description: Smart Actions Library for Siri shortcuts and Google Assistant routines.
version: 0.1.0+1
publish_to: none
homepage: 

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: SmartActionsPlugin
      android:
        package: co.modestnerds.smart_actions
        pluginClass: SmartActionsPlugin